import type { Metadata } from 'next';
import { Providers } from '@/components/providers';
import localFont from 'next/font/local';
import '@/styles/globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { cn } from '@/lib/utils';
import ScrollToTopButton from '@/components/layout/ScrollToTopButton';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import Container from '@/components/layout/Container';

// 폰트 설정
const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'OnRace',
  description: 'Generated by six-sense',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body
        className={cn('antialiased', pretendard.className)}
        suppressHydrationWarning={true}
      >
        <Providers>
          <ReactQueryProvider>
            <div className="flex flex-col min-h-screen">
              <Header />

              <main className="flex-1 bg-white content-center">
                <Container>{children}</Container>

                <ScrollToTopButton />
              </main>

              <Footer />
            </div>
          </ReactQueryProvider>
        </Providers>
      </body>
    </html>
  );
}
